<a href="https://colab.research.google.com/github/Tanzeela00Sharif/python-notebooks-collection/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

##creating Numpy array

In [2]:
#np.array
import numpy as np
#1D array is vector
a=np.array([1,2,3])
print(a)
print(type(a))

[1 2 3]
<class 'numpy.ndarray'>


In [3]:
#2D and 3D array
#2D array is called metrix
b=np.array([[12,13],[14,15]])
print(b)
print(type(b))

[[12 13]
 [14 15]]
<class 'numpy.ndarray'>


In [4]:
#3D array is called tensor
c=np.array([[[1,2],[3,4]],[[12,13],[14,15]]])
print(c)

[[[ 1  2]
  [ 3  4]]

 [[12 13]
  [14 15]]]


In [5]:
np.array([1,2,3],dtype=float)

array([1., 2., 3.])

In [6]:
np.array([0,2,3],dtype=bool)

array([False,  True,  True])

In [7]:
np.array([1,2,3],dtype=complex)

array([1.+0.j, 2.+0.j, 3.+0.j])

In [8]:
#np.arrange()
#first digit is included and last one is excluded
np.arange(1,12)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [9]:
# first one is row number while is second one is the column number
#if not possible it throw an error
np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

###np. initialize values

In [10]:
#np.ones
#first one is row number while the second one is column number
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [11]:
#np.zeros
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [12]:
#np.random
np.random.random((1,3))

array([[0.7913112 , 0.18093395, 0.11651293]])

In [13]:
#print the values between two extremes
np.linspace(10,-10,12)

array([ 10.        ,   8.18181818,   6.36363636,   4.54545455,
         2.72727273,   0.90909091,  -0.90909091,  -2.72727273,
        -4.54545455,  -6.36363636,  -8.18181818, -10.        ])

In [14]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

##Atributes of numpy array

In [15]:
import numpy as np

In [16]:
a1=np.arange(10,dtype=np.int32)
a2=np.arange(12,dtype=float).reshape(3,4)
a3=np.arange(16, dtype=int).reshape(2,2,2,2)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)

In [17]:
# to check tthe number of dimension of an array we ndim
print(a1.ndim)
print(a2.ndim)
print(a3.ndim)

1
2
4


In [18]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(10,)
(3, 4)
(2, 2, 2, 2)


In [19]:
#check the size of any array
print(a1.size)
print(a2.size)
print(a3.size)

10
12
16


In [20]:
from ast import Raise
#check the itemsize or memory size of each item of the array occupy in RAM ,32bits or 64 bits
#32bits==4bytes or
#64 bits==8bytes
print(a1.itemsize)
print(a2.itemsize)
print(a3.itemsize)

4
8
8


In [21]:
#check the data types in array
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int32
float64
int64


##changing the data type

In [22]:
#astype
a4=a3.astype(np.int32)
a4

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]], dtype=int32)

In [23]:
print(a3.dtype)
print(a4.dtype)

int64
int32


##Operation on metrix

In [24]:
#scalar operation on mitrix or 2D array
print(a2)

#multiplication
print('\n', a2 *2)

#addition
print('\n',a2 + 5)

#division
print('\n',a2 / 5)

#substraction
print('\n',a2 - 5)

#square
print('\n',a2 ** 2)

[[ 0.  1.  2.  3.]
 [ 4.  5.  6.  7.]
 [ 8.  9. 10. 11.]]

 [[ 0.  2.  4.  6.]
 [ 8. 10. 12. 14.]
 [16. 18. 20. 22.]]

 [[ 5.  6.  7.  8.]
 [ 9. 10. 11. 12.]
 [13. 14. 15. 16.]]

 [[0.  0.2 0.4 0.6]
 [0.8 1.  1.2 1.4]
 [1.6 1.8 2.  2.2]]

 [[-5. -4. -3. -2.]
 [-1.  0.  1.  2.]
 [ 3.  4.  5.  6.]]

 [[  0.   1.   4.   9.]
 [ 16.  25.  36.  49.]
 [ 64.  81. 100. 121.]]


In [25]:
#relational operators
a2 >7
a2<3
a2==10
a2!=10

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False,  True]])

##Operation on vectors

these operations are operation which apply on two different metrix or vectors with same shape.



In [26]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [27]:
a2.dtype

dtype('float64')

In [28]:
a5=np.arange(12,dtype=int).reshape(3,4)
a5


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [29]:
#arithmetic
a2 /5

array([[0. , 0.2, 0.4, 0.6],
       [0.8, 1. , 1.2, 1.4],
       [1.6, 1.8, 2. , 2.2]])

In [30]:
a6=np.random.random((3,3))
a6=np.round(a6*100)
a6

array([[25., 17., 37.],
       [50., 17., 21.],
       [49., 76., 50.]])

In [31]:
#min,max,sum,product

np.max(a6)
np.min(a6)
np.sum(a6)
np.prod(a6)


np.float64(52264710750000.0)

In [32]:
#extract the element from each row and column
#column->0  , row->1
np.sum(a6,axis=0)

array([124., 110., 108.])

In [33]:
#statistical operations in numpy
#mean, median, std, variance

a6
np.mean(a6 ,axis=0)

array([41.33333333, 36.66666667, 36.        ])

In [34]:
#median
np.median(a6,axis=1)

array([25., 21., 50.])

In [35]:
#std deviation
np.std(a6)

np.float64(18.83849486792639)

In [36]:
#variance
np.var(a6)

np.float64(354.8888888888889)

In [37]:
#trignometric functions
np.sin(a6)
np.cos(a6)


array([[ 0.99120281, -0.27516334,  0.76541405],
       [ 0.96496603, -0.27516334, -0.54772926],
       [ 0.30059254,  0.82433133,  0.96496603]])

In [38]:
#dot product
a=np.arange(48,60).reshape(3,4)
b=np.arange(12,24).reshape(4,3)
np.dot(a,b)




array([[3282, 3480, 3678],
       [3546, 3760, 3974],
       [3810, 4040, 4270]])

In [39]:
#log and exponent
np.log(a)
np.exp(a)

array([[7.01673591e+20, 1.90734657e+21, 5.18470553e+21, 1.40934908e+22],
       [3.83100800e+22, 1.04137594e+23, 2.83075330e+23, 7.69478527e+23],
       [2.09165950e+24, 5.68572000e+24, 1.54553894e+25, 4.20121040e+25]])

In [40]:
#floor,round, ceil
a=(np.random.random((2,3))*100)
a
#np.ceil(a)

array([[51.90316799, 27.09004567, 79.05530674],
       [35.10730015, 71.56706327, 71.72756941]])

In [41]:
a

array([[51.90316799, 27.09004567, 79.05530674],
       [35.10730015, 71.56706327, 71.72756941]])

In [42]:
np.round(a)

array([[52., 27., 79.],
       [35., 72., 72.]])

In [43]:
np.floor(a)

array([[51., 27., 79.],
       [35., 71., 71.]])

In [44]:
np.ceil(a)

array([[52., 28., 80.],
       [36., 72., 72.]])

##Slicing and Indexing

In [46]:
a1=np.arange(12,24).reshape(4,3)
a1


array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [50]:
#indexing start in array from 0 row and 0 column
a1[0,1]
a1[2,1]

np.int64(19)

In [51]:
a3

array([[[[ 0,  1],
         [ 2,  3]],

        [[ 4,  5],
         [ 6,  7]]],


       [[[ 8,  9],
         [10, 11]],

        [[12, 13],
         [14, 15]]]])

In [53]:
a3[1,1,1,1]

np.int64(15)

In [56]:
a=np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
#slicing in 1D
a[2:8]
a[-1]
a[-3]

np.int64(7)

In [54]:
#slicing
a1

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

In [61]:
#fetch any row
a1[0,:]
a1[2,:]

array([18, 19, 20])

In [72]:
a1[0:2,1:]

array([[13, 14],
       [16, 17]])

In [68]:
a1[2,0::2]

array([18, 20])

In [63]:
#fetch any column
a1[:,0]
a1[:,2]

array([14, 17, 20, 23])

In [67]:
a1[::3,::2]

array([[12, 14],
       [21, 23]])

In [64]:
a1[2:,1:]

array([[19, 20],
       [22, 23]])

In [66]:
a1[1:3,0:2]

array([[15, 16],
       [18, 19]])

In [73]:
a3=np.arange(27).reshape(3,3,3)

a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [84]:
a3[0::2]
a3[::2]

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [87]:
a3[::2,0,::2]

array([[ 0,  2],
       [18, 20]])

In [86]:
a3[2,1:,1:,]

array([[22, 23],
       [25, 26]])

In [82]:
a3[1,1,]

array([12, 13, 14])

In [83]:
a3[1,::,1]

array([10, 13, 16])

##iteration

In [92]:
a1=np.arange(0,10)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [93]:
for i in a1:
  print(i)

0
1
2
3
4
5
6
7
8
9


In [89]:
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [95]:
for i in a2:
  print(i)

[0. 1. 2. 3.]
[4. 5. 6. 7.]
[ 8.  9. 10. 11.]


In [90]:
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [97]:
for i in a3:
  print(i)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[18 19 20]
 [21 22 23]
 [24 25 26]]


In [99]:
for i in np.nditer(a3):
  print(i)

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26


##Reshaping

In [ ]:
#reshape

In [102]:
#transpose
#(3,4)
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [103]:
a2.T

array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.]])

In [101]:
#reshape to 4,3
a2.transpose()

array([[ 0.,  4.,  8.],
       [ 1.,  5.,  9.],
       [ 2.,  6., 10.],
       [ 3.,  7., 11.]])

In [104]:
#ravel function convert any dimension array into 1D array
a3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [106]:
a3.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

##Stacking
###shape must be same
use to join the different arrays with same shape horizontly and vertically

In [109]:
a5=np.arange(12).reshape(3,4)
a6=np.arange(12,24).reshape(3,4)
a6

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [117]:
#horizontal stacking
a5=np.hstack((a5,a6))
a5


array([[ 0,  1,  2,  3, 12, 13, 14, 15, 12, 13, 14, 15, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19, 16, 17, 18, 19, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23, 20, 21, 22, 23, 20, 21, 22, 23]])

In [113]:
#Vertical stacking
np.vstack((a5,a6,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

##Spliting

split the array in same shape and equal part

In [118]:
a5

array([[ 0,  1,  2,  3, 12, 13, 14, 15, 12, 13, 14, 15, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19, 16, 17, 18, 19, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23, 20, 21, 22, 23, 20, 21, 22, 23]])

In [120]:
a6=np.arange(12,24).reshape(3,4)
a6

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [121]:
np.hsplit(a6,2)

[array([[12, 13],
        [16, 17],
        [20, 21]]),
 array([[14, 15],
        [18, 19],
        [22, 23]])]

In [122]:
a5=np.arange(16).reshape(4,4)

In [123]:
np.vsplit(a5,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]